### Training Configuration ###
exp_name         : # Where to store logs and models
train_data       : indonesia_dataset/train                # path to train dataset
valid_data       : indonesia_dataset/valid                # path to valid dataset
test_data        : indonesia_dataset/test                 # path to test dataset
image_folder     : indonesia_dataset/test                 # path to image folder for predict
manualSeed       : 1111                                   # for random seed setting
workers          : 24                                     # number of data loading workers
batch_size       : 128                                    # input batch size
num_epoch        : 1000                                   # number of iterations to train for
saved_model      : saved_models/best.ckpt                 # path to model to continue training
adam             : false                                  # Whether to use adam (default is Adadelta)
lr               : 1                                      # learning rate, default=1.0 for Adadelta
beta1            : 0.9                                    # beta1 for adam. default=0.9
rho              : 0.95                                   # decay rate rho for Adadelta. default=0.95
eps              : .00000001                              # eps for Adadelta. default=1e-8
grad_clip        : 5                                      # gradient clipping value. default=5
scheduler        : true                                   # use scheduler or not
swa_lrs          : .01                                    # stochastic weight averaging learning rate.

### Data processing ###
batch_max_length : 10                                     # maximum-label-length
imgH             : 224                                    # the height of the input image
imgW             : 224                                    # the width of the input image
rgb              : false                                  # use rgb input
character        : '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' # character label
PAD              : false                                  # whether to keep ratio then pad for image resize

### Model Architecture ###
model_name       : "vitstr_small_patch16_224"
num_fiducial     : 20                                     # number of fiducial points of TPS-STN
