### Training Configuration ###
exp_name         : # Where to store logs and models
data_root        : "/home/fourind/projects/datas/indonesia-datas/"
manualSeed       : 20230323                                   # for random seed setting
workers          : 24                                     # number of data loading workers
batch_size       : 128                                    # input batch size

num_epoch        : 1000                                   # number of iterations to train for
saved_model      : saved_models/ViTSTR-Seed20230323/best.pt                 # path to model to continue training
adam             : false                                  # Whether to use adam (default is Adadelta)
lr               : 1                                      # learning rate, default=1.0 for Adadelta
beta1            : 0.9                                    # beta1 for adam. default=0.9
rho              : 0.95                                   # decay rate rho for Adadelta. default=0.95
eps              : .00000001                              # eps for Adadelta. default=1e-8
grad_clip        : 5                                      # gradient clipping value. default=5
scheduler        : true                                   # use scheduler or not
swa_lrs          : .01                                    # stochastic weight averaging learning rate.
swa_epoch_start  : 5
pad              : false
kor              : false                                  # use kor character
